### ISSUE TITLE
Improvement: Use bfloat16

### ISSUE THREAD

**Issue by PhilipMay** [Leeroo-AI/mergoo#11]
Hi,

in this notebook you merge 3 experts to a MoE:
https://github.com/Leeroo-AI/mergoo/blob/main/notebooks/integrate_phi3_experts.ipynb

You store them in float16 format. 2 experts are in bfloat16 format and one in float32.

IMO it would be better to use bfloat16 in this case instead of float16.

What do you think?

Thanks,
Philip

**Comment by gitsailor5** [comment]
@PhilipMay That's just an example notebook we hacked in a few hours. Feel free to improve it and submit a pull request.
btw It's always better to have consistent weights, but when you load the weights, everything gets converted to the desired format.
