### ISSUE TITLE
Possibility to integrate multiple model types?

### ISSUE THREAD

**Issue by sammcj** [Leeroo-AI/mergoo#16]
It would be neat if Mergoo could integrate multiple model types.

For example a great MoM for technical tasks might be something like:

- Llama 3 8b
- Phi 3 Medium 128k
- CodeQwen1.5 7b
- Nxcode-CQ-7B-orpo

Is this technically possible with Mergoo?

**Comment by alirezamshi** [comment]
Hi,

For the integration with mergoo, fine-tuned experts must have the same architecture. For model-wise integration, please check our router library (https://github.com/Leeroo-AI/leeroo_orchestrator).

**Comment by sammcj** [comment]
That's really helpful, thank you for your response Alireza. 😄
