### ISSUE TITLE
How many H100-80GB devices Needed for Merging and Tuning a Llama 3-based MoE Model?

### ISSUE THREAD

**Issue by jacklanda** [Leeroo-AI/mergoo#6]
I love this amazing project!

Two remaining questions
- How many H100/A100 80GB GPUs should I use to conduct merging and fine-tuning experiments on Mergoo 🤔?
- Does Mergoo support building the MoE model based on Llama 3?

**Comment by jacklanda** [comment]
By the way, I would like to contribute to this project ☺️.

Could I file PRs for the enhancement directly for it? Thanks so much!

**Comment by alirezamshi** [comment]
Thanks for your interest. 

For the compute, it depends on your MoE method, e.g. Mixture-of-Adapters or MoE + typical MoE. The latter requires GPUs with larger memory as feed-forward layers are multipled by the number of merged experts. 

Yes, mergoo supports LLaM3 based experts. Please check the tutorial [here](https://github.com/Leeroo-AI/mergoo/blob/main/notebooks/integrate_llama3_experts.ipynb).

For the contribution, feel free to PR directly :)
